version: '3'
services:
  postgres:
    image: postgres:14
    container_name: blockchain-tracker-db
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - blockchain-network

  app:
    build: .
    container_name: blockchain-tracker-app-api
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - blockchain-network

networks:
  blockchain-network:
    driver: bridge

volumes:
  pgdata:
